// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoyNI0yBYHbL8I6n2oMLj5PwLxxBD7SI',
    appId: '1:349132973604:web:007d6e6925290a6d459ab1',
    messagingSenderId: '349132973604',
    projectId: 'flights-f05f8',
    authDomain: 'flights-f05f8.firebaseapp.com',
    storageBucket: 'flights-f05f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtC3E_6z6b1vAUnEsZyg0RSzIOpBW3Mhs',
    appId: '1:349132973604:android:a10918c6e14523d4459ab1',
    messagingSenderId: '349132973604',
    projectId: 'flights-f05f8',
    storageBucket: 'flights-f05f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--mpPQYsxa_ol7-Q7WpxhJf6dUdLVsls',
    appId: '1:349132973604:ios:08b8970e710320dc459ab1',
    messagingSenderId: '349132973604',
    projectId: 'flights-f05f8',
    storageBucket: 'flights-f05f8.appspot.com',
    iosBundleId: 'com.example.flights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--mpPQYsxa_ol7-Q7WpxhJf6dUdLVsls',
    appId: '1:349132973604:ios:0f518930059af1d7459ab1',
    messagingSenderId: '349132973604',
    projectId: 'flights-f05f8',
    storageBucket: 'flights-f05f8.appspot.com',
    iosBundleId: 'com.example.flights.RunnerTests',
  );
}
